config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  # **バリデーション
  validates :user_id, presence: true
  validates :post_id, presence: true

  # validates_uniqueness_of :post_id, scope: :user_id

  # def already_liked?(post)
  #   self.likes.exists?(post_id: post.id)
  # end

  # **アソシエーション
  belongs_to :user
  belongs_to :post
end

app/models/parking_fee.rb
class ParkingFee < ActiveHash::Base
  self.data = [
    { id: 1,   name: '---' },
    { id: 2,   name: '有料（通年）' },
    { id: 3,   name: '有料（一部時期）' },
    { id: 4,   name: '無料' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/parking_presence.rb
class ParkingPresence < ActiveHash::Base
  self.data = [
    { id: 1,   name: '---' },
    { id: 2,   name: 'あり' },
    { id: 3,   name: 'なし' },
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  # 撮影地の登録時に、geocoderが緯度、経度を自動で登録する設定
  geocoded_by :shooting_location
  after_validation :geocode, if: :shooting_location_changed?
  
  # def liked_by?(user)
  #   likes.where(user_id: user.id).exists?
  # end

  def liked_by?(current_user)
    likes.where(user_id: user.id).exists?
  end
  

  # **バリデーション
  validates :title,               presence: true, length: { maximum: 40 }
  validates :shooting_month_id,   presence: true
  validates :shooting_week,       presence: true
  validates :impression_point,    presence: true
  # validates :parking_presence_id, presence: true
  # validates :parking_fee_id,      presence: true 
  # validates :nearest_station,     presence: true
  # validates :walking_time_id,     presence: true
  validates :shooting_location,   presence: true
  # validates :other_information
  validates :image,               presence: true

  # ** ジャンルの選択が「---」の時は保存できないようにする
  validates :shooting_month_id,   numericality: { other_than: 1, message: "can't be blank" }
  validates :shooting_week_id,    numericality: { other_than: 1, message: "can't be blank" }
  # validates :parking_presence_id, numericality: { other_than: 1, message: "can't be blank" }
  # validates :parking_fee_id,      numericality: { other_than: 1, message: "can't be blank" }
  # validates :walking_time_id,     numericality: { other_than: 1, message: "can't be blank" }

  # ** テーブル間のアソシエーション
  belongs_to       :user
  has_many         :comments
  has_many         :likes, dependent: :destroy
  has_one_attached :image

  # ActiveHashとのアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :shooting_month
  belongs_to :shooting_week
  belongs_to :parking_presence
  belongs_to :parking_fee
  belongs_to :walking_time
end

app/models/shooting_month.rb
class ShootingMonth < ActiveHash::Base
  self.data = [
    { id: 1,   name: '---' },
    { id: 2,   name: '1月' },
    { id: 3,   name: '2月' },
    { id: 4,   name: '3月' },
    { id: 5,   name: '4月' },
    { id: 6,   name: '5月' },
    { id: 7,   name: '6月' },
    { id: 8,   name: '7月' },
    { id: 9,   name: '8月' },
    { id: 10,  name: '9月' },
    { id: 11,  name: '10月' },
    { id: 12,  name: '11月' },
    { id: 13,  name: '12月' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/shooting_week.rb
class ShootingWeek < ActiveHash::Base
  self.data = [
    { id: 1,   name: '---' },
    { id: 2,   name: '上旬' },
    { id: 3,   name: '中旬' },
    { id: 4,   name: '下旬' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :user_name, presence: true

  # アソシエーション
  has_many :posts,    dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes,    dependent: :destroy

  # 既にいいねしているか判定するメソッドを定義
  # def already_liked?(post)
  #   self.likes.exists?(post_id: post.id)
  # end

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end
end

app/models/walking_time.rb
class WalkingTime < ActiveHash::Base
  self.data = [
    { id: 1,   name: '---' },
    { id: 2,   name: '5分以内' },
    { id: 3,   name: '5分〜15分未満' },
    { id: 4,   name: '15分〜30分未満' },
    { id: 5,   name: '30分〜1時間未満' },
    { id: 6,   name: '1時間以上' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '1111'
    end
  end

  def configure_permitted_parameters  
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :email, :encrypted_password])
  end
end 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # Comment.create(comment_params)             //ActionCable導入により削除
    # redirect_to post_path(params[:post_id])    //ActionCable導入により削除

    @comment = Comment.new(comment_params)
    if @comment.save
      @post = Post.find(params[:post_id])
      CommentChannel.broadcast_to @post, { comment: @comment, user: @comment.user }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end
  
  # def create
  #   @like = current_user.likes.create(post_id: params[:post_id])
  #   redirect_back(fallback_location: root_path)
  # end

  # def destroy
  #   @post = Post.find(params[:post_id])
  #   @like = current_user.likes.find_by(post_id: @post.id)
  #   @like.destroy
  #   redirect_back(fallback_location: root_path)
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show] 

  def index
    @posts = Post.order('id DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
     redirect_to root_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :shooting_month_id, :shooting_week_id, :impression_point, :parking_presence_id, :parking_fee_id, 
                                 :nearest_station, :walking_time_id, :shooting_location, :other_information, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    # @posts = @user.posts
    @posts = Post.order('id DESC')  

    likes= Like.where(user_id: @user.id).pluck(:post_id)
    @like_posts = Post.find(likes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like_index.html.erb
<td>
	<p class="caption"><%#= post.locate %>
    <%# if current_user.liked_by?(post.id) %>
    <%# if current_user.already_liked?(post) %>

    <% if post.liked_by?(current_user) %>
    <%= link_to post_likes_path(id: post.id, post_id: post.id), method: :delete, remote: true, class: "like_btn" do %>
      行きたい <i class="fas fa-thumbs-up fa-2x" style="color: black;"></i> <%= post.likes.count %> 
    <% end %>
    <% else %>
      <%= link_to post_likes_path(id: post.id, post_id: post.id), method: :post,remote: true,  class: "like_btn" do %>
      行きたい <i class="far fa-thumbs-up fa-2x" style="color: black;"></i><%= post.likes.count %>
      <% end %>
    <% end %>
  </p>
</td>

app/views/likes/_like_show.html.erb
<td>
	<p class="caption"><%#= post.locate %>
    <%# if current_user.liked_by?(post.id) %>
    <%# if current_user.already_liked?(@post) %>

    <% if @post.liked_by?(current_user) %>
    <%= link_to post_likes_path(@post), method: :delete, remote: true, class: "like_btn" do %>
      行きたい <i class="fas fa-thumbs-up fa-2x" style="color: black;"></i> <%= @post.likes.count %> 
    <% end %>
    <% else %>
      <%= link_to post_likes_path(@post), method: :post,remote: true,  class: "like_btn" do %>
      行きたい <i class="far fa-thumbs-up fa-2x" style="color: black;"></i> <%= @post.likes.count %>
      <% end %>
    <% end %>
  </p>
</td>

app/views/likes/create.js.erb
<!-- #like_area_<%= @post.id %>この部分のHTMLだけ、renderで部分的に更新するという処理 -->
$("#like_btn_<%= @post.id %>").html("<%= j(render partial: 'likes/like_show', locals: { post: @post }) %>");

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <div class='title-contents'>
    <div class='concept'>
      「感動の1枚」を、推そう
    </div>
    <div class='concept'>
      「感動の1枚」を、観に行こう
    </div>
  
    <div class='backgound-explanation'>
      <div class='explanation'>
        雄大な「富士山」「五重塔」「桜」を一目に見ることができ"NIPPON"を体感できると海外からも大絶賛のSPOTです。<br>
        新倉山の中腹にあり、398段の階段を登るプチ登山の後に見る景色は、一見の価値があります。
      </div>
      <div class='location'>
        山梨県 新倉山浅間公園（4月中旬ごろ）
      </div>
    </div>
  </div>
 
  <div class='item-contents'>

  <div class='posts-map'>
      <%# Google map %>
  <div id='map'></div>

   <style>
#map {
  height: 600px;
  width: 100%;
}
</style>
<script>
    function initMap() {

      //初期表示位置：東京駅
      let latlng = new google.maps.LatLng(35.68114292160832, 137.76699220422807);
      //デザイン
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 8,　　//倍率を決める
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);


      <% @posts.each do |post| %>
          (function(){
          var contentString = "タイトル：<%= post.title %>"; // マーカーにポインターを重ねた時に表示する小さい吹き出しの中身を定義

          var marker = new google.maps.Marker({
              position:{lat: <%= post.latitude %>, lng: <%= post.longitude %>},
              map: map,
              title: contentString // 上で定義した吹き出しの中身を呼び出す（title →小さなグレーの吹き出し）
          });
          var contentString = 'タイトル：<%= post.title %><br>撮影地：<%= post.shooting_location %><br>撮影時期:<%= post.shooting_month.name %><%= post.shooting_week.name %><br><%= link_to '詳細ページ', post_path(post.id) %>';// マーカーにポインターをクリックした時に表示する吹き出しの中身を定義
          var infoWindow = new google.maps.InfoWindow({ // 吹き出しの追加
            content: contentString // 上で定義した吹き出しの中身を呼び出す（content →大きい白色の吹き出し）
          });
          marker.addListener('click', function() { // マーカーをクリックしたとき
              infoWindow.open(map, marker); // 吹き出しを表示
          });
          })();
      <% end %>
      //複数マーカー ここまで  
  }
</script>
      <script async defer
      <%# envファイルからのキー取得 %>
        <%# src="https://maps.googleapis.com/maps/api/js?v=3.exp&key= %>
        <%#= ENV['GOOGLE_MAP_API_KEY'] %>
        <%# &callback=initMap"> %>

      <%# credentials.yml.encファイルからキー取得 %>
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= Rails.application.credentials.google_map_api_key %>&callback=initMap">
      </script>
    </div>

    <div class='title'>Photograph</div>
    <div class="subtitle" >
    </div>
    <ul class='item-lists'>
      <% @posts.each do |post| %>
        <li class='list'>
         <%= link_to post_path(post.id) do %>
          <div class='post-img-content'>
            <%= image_tag post.image, class: "post-img" %>
              <%# <div class='item-info'> %>
                <div class='post-title-show'>
                  <%= post.title %>
                </div>
              <%# </div> %>
          </div>
        <% end %>
          
        <div class='contributor'>  
          <%= link_to post.user.user_name, user_path(post.user), class: "contributor" %>
        </div>
        <div class='like'>  
          <%#= link_to post.user.user_name, user_path(post.user) 行きたいを載せる%> 
          <div id="like_btn_<%= post.id %>">
            <%= render 'likes/like_index', post: post %>
			    </div>
        </div>
      <% end %>
      </li>
    </ul>
  </div> 

</div>
<%= link_to(new_post_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>  </span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/posts/new.html.erb
<div class="post-contents">
  <header class="post-header">
    <%# link_to image_tag('impression spot-logo-color.png' , size: '300x50'), "/" %>

  </header>
  <div class="post-main">
    <h2 class="new-post-title">投稿ページ</h2>
    <%= form_with model: @post, url: posts_path, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="label-text">
        感動の1枚
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          <%# クリックしてファイルをアップロード %>
        </p>
        <%= f.file_field :image, id:"post-image" %>
      </div>
    </div>

    <div class="new-post">
      <div class="label-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"title-form", id:"title-form", placeholder:"例）新倉山浅間公園", maxlength:"40" %>
      
      <div class="post-explain">
        <div class="label-text">
          感動ポイント
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :impression_point, class:"impression-spot-form", id:"impression-spot-form", placeholder:"例）富士山、五重塔、桜を一目に見ることができます" ,rows:"5" ,maxlength:"1000" %>
      </div>
    </div>

     <div class="post-detail"> 
      <div class="label-text">
        撮影時期
        <span class="indispensable">必須</span>
      </div>
      <div class="form">
        <div class="label-text">
          撮影月
          <span class="indispensable">必須</span>
        </div>  
        <%= f.collection_select(:shooting_month_id, ShootingMonth.all, :id, :name, {}, {class:"select-box", id:"shooting_month"}) %>
         <div class="label-text">
          撮影週  
          <span class="indispensable">必須</span>
        </div> 
        <%= f.collection_select(:shooting_week_id, ShootingWeek.all, :id, :name, {}, {class:"select-box", id:"shooting_week"}) %>
      </div>
    </div>

    <div class="post-detail">
      <div class="label-text">周辺の駐車場（任意）</div>
      <div class="form">
        <div class="label-text">
          駐車場の有無（任意）
        </div>

        <%= f.collection_select(:parking_presence_id, ParkingPresence.all, :id, :name, {}, {class:"select-box", id:"parking_presence"}) %>
        <div class="label-text">
          駐車場代（任意）
        </div>
        <%= f.collection_select(:parking_fee_id, ParkingFee.all, :id, :name, {}, {class:"select-box", id:"parking_fee"}) %>
      </div>
    </div>

    <div class="post-detail">
      <div class="label-text">公共交通機関（任意）</div>
      <div class="form">
        <div class="label-text">
          最寄り駅（任意）
        </div>
        <%= f.text_area :nearest_station, class:"nearest_station-form", id:"nearest_station", placeholder:"例）下吉田駅", rows:"2", maxlength:"40" %>

        <div class="label-text">
          最寄り駅からの徒歩時間（任意）
        </div>
        <%= f.collection_select(:walking_time_id, WalkingTime.all, :id, :name, {}, {class:"select-box", id:"walking_time"}) %>
      </div>
    </div>

    <div class="new-post">
      <div class="label-text">
        撮影地の住所
        <span class="indispensable">必須</span>
        <a class="gmap-link-btn" href='https://www.google.co.jp/maps/@35.6811429216083,139.76699220422807' target="_blank" rel="noopener noreferrer">
           <%= image_tag("icons8-google-maps-48.png", class:"gmap-icon")%>
          Googleマップで検索
        </a>
      </div>  
      <%= f.text_area :shooting_location, class:"shooting_location-form", id:"shooting_location", placeholder:"例）山梨県富士吉田市浅間２−３３５３",rows:"2", maxlength:"40" %>

      <div class="label-text">
        補足情報
      </div>  
      <%= f.text_area :other_information, class:"other-information-form", id:"other_information", placeholder:"例）桜のシーズン(4月上旬〜中旬)に行く方へ
      ・駐車場は有料(1000円)です。園外の周辺には臨時駐車場が設置されます。
      ・臨時駐車場からはシャトルバスが運行します。
      ・6:00〜8:00に展望デッキを利用する際は、事前予約チケット(抽選)の購入が必要です。
      " ,rows:"7" ,maxlength:"1000"%>

    </div>
    <div class="btn-contents">
      <%= f.submit "投稿する", class:"post-btn" %>
      <%= link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class='post-show-page-main'>
  <div class='post-box'>
    <div class='image-map-area'>
      <div class="post-image">
        <div class="post-title">
          <%= @post.title %>
        </div>
        <%= image_tag @post.image, class: 'image_size' %>
      </div>
        <div class="shooting-location-map">

        <script type="text/javascript">
          function initMap() {
            // latitude,longitudeから位置を特定
            var test ={lat: <%= @post.latitude %>, lng: <%= @post.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
                      zoom: 15, 
                      center: test    
                      });
            var transitLayer = new google.maps.TransitLayer();
            transitLayer.setMap(map);

            var contentString = '撮影地：<%= @post.shooting_location %>';
            var infowindow = new google.maps.InfoWindow({
              content: contentString
            });

            //  Map上の指定した位置にピンを挿して表示する
            var marker = new google.maps.Marker({
                          position:test,
                          map: map,
                          title: contentString
                        });

            marker.addListener('click', function() {
              infowindow.open(map, marker);
            });
          }
        </script> 

        <%# 以下の記述の中にあるYOUR_API_KEYには取得したご自身のAPIキーを記述してください %>
        <script async defer
                      src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
        </script>
        <%# 表示するmapのcssです。ご自身でカスタマイズしてください。高さが設定されていないと表示されないことがあります。 %>
        <style type="text/css">
          #map { height: 100%;
                 width: 100%;}
        </style>

       <%# mapの表示 %>
        <div id="map"></div>

      </div>
    </div>

    <div class='go-icon-area'>

      <div class='wanna-go-area'>
        <%# <div class='wanna-go-text'> %>
          <div id="like_btn_<%= @post.id %>">
            <%= render 'likes/like_show', post: @post %>
			    </div>

        <%# </div> %>
        <%# <div class='wanna-go-icon-area'> %>
          <%#= link_to image_tag("wanna_go_icon.png", class:"wanna-go-icon"), "#" %>
        <%# </div> %>
         <%# <div class='wanna-go-count'>
          
        </div> %>
      </div>

      <%# <div class='went-area'> %>
        <%# <div class='went-text'>
          <div>行った！</div>
        </div>
        <div class='went-icon-area'> %>
          <%#= link_to image_tag("went_icon.png", class:"went-icon"), "#" %>
        <%# </div> %>
        <%# <div class='went-count'>
        </div>
      </div> %>
    </div>

    <div class='comment-area-main'>
      <div class='comment-area-sub'>
      
        <%# コメント入力欄 %>
        <div class='comment-form-area'>
          <% if user_signed_in? %>
            <%= form_with model: [@post, @comment], id: "comment-form" do |f| %>  <%# id: "comment-form" はJSファイルで流用中 %>
              <%= f.text_area :text, style: "width:100%", placeholder: "コメントを追加" %>
              <%= f.submit "コメント",class: "comment-btn" %>
            <% end %>
          <% else %>
            <%# <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong> %>
          <% end %>
        </div>

        <%# <div class='btn-area'> %>
          <%# <div class='cancel-btn'>
             <div>キャンセル</div>
          </div> %>
          <%# <div class='comment-btn'>
          <div>コメント</div> %>
          <%# </div> %>
        <%# </div> %>
      </div>

      <div class='comment-display-area' id="comments"> <%#  id="comments" はJSファイルで流用中 %>
        <%# <h4>＜コメント一覧＞</h4> %>
          <% @post.comments.reverse_each do |comment| %>
            <%# 以下のコードは、JSファイルでも流用中 %>
            <div class='comment-row'>
              <div class='commenter'><%= comment.user.user_name %>： </div>
              <div class='comment-sentence'><%= comment.text %></div>
            </div>
            <%# 以上のコードは、JSファイルでも流用中 %>
          <% end %>
      </div>
    </div>  


    <div class='post-detail-area-main'>
      <div class='post-detail-area-sub'>

        <div class='impression-point'>
          <div class='detail-title-01'>
          感動ポイント
          </div>
          <div class='detail-sentence-01'>
            <%= @post.impression_point %>
          </div>
        </div>

        <div class='shooting-season'>
          <div class='detail-title-01'>
          撮影時期
          </div>
          <div class='detail-sentence-01'>
            <%= @post.shooting_month.name  %><%= @post.shooting_week.name  %>
          </div>
        </div>

        <div class='shooting-location'>
          <div class='detail-title-01'>
           撮影地
          </div>
          <div class='detail-sentence-01'>
            <%= @post.shooting_location %>
          </div>
        </div>

        <div class='parking'>
          <div class='detail-title-02'>
          周辺の駐車場
          </div>
          <div class='detail-sentence-02'>
            <div class='detail-sentence-row1'>  
              <%= @post.parking_presence.name %>
            </div>
            <div class='detail-sentence-row2'>
              <%= @post.parking_fee.name %>
            </div>
          </div>
        </div>

         <div class='public-transport'> 
          <div class='detail-title-03'>
          最寄りの公共交通機関
            <div class='detail-title-row1'>
            駅名
            </div>
            <div class='detail-title-row2'>
            駅からの徒歩時間
            </div>
            <div class='detail-title-row3'>
            </div>
          </div>
          <div class='detail-sentence-03'>
            <div class='detail-sentence-row1'>
            </div>
            <div class='detail-sentence-row2'>
              <%= @post.nearest_station %>
            </div>
            <div class='detail-sentence-row3'>
              <%= @post.walking_time.name %>
            </div>
          </div>
        </div>

        <div class='other-information'>
          <div class='detail-title-other'>
          補足情報
          </div>
          <div class='detail-sentence-other'>
            <%= @post.other_information %>
          </div>
        </div>
      </div>
      


      <div class='user-btn-area'>
        <div class='edit-btn'>
          <%= link_to '編集', edit_post_path(@post.id), class:"edit-btn" %>
        </div>
        <div class='delete-btn'>
          <%= link_to '削除', post_path(@post.id), method: :delete, class:"delete-btn" %>
        </div>
      </div>
    </div>


    <%# <div>あいうえお</div>
    <div>あいうえお</div>  %>
  </div>

</div>


<%# <div class='main'> %>

  <%#= "#{@user.user_name}さんの投稿一覧" %>
 <%# <div class='post-contents'> %>
    <%# <h2 class='title'> %>
    <%#= "#{@user.user_name}さんのPhotograph" %> 
    
    <%# </h2> %>
    <%# <ul class='post-lists'> %>
      <%# @posts.each do |post| %>
        <%# <li class='list'> %>
         <%#= link_to 'post_path(post.id)' do %>
         <%# <div class='post-img-content'> %>
          <%#= image_tag post.image, class: "post-img" %>
          <%# end %>
       
      <%# </div>
        <div class='post-info'>
          <h3 class='post-name'> %>
            <%#= post.title %>
          <%# </h3> %>
      
        <%# </li> %>
      <%# end %>
    <%# </ul> %>
  <%# </div> %>
<%= render "shared/footer" %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("impression spot-logo-color.png", class:"furima-icon"), root_path %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから感動の1枚を探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%#= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%#= link_to 'ブランド', "#", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
        
      <% if user_signed_in? %>  
        <li><%= link_to 'マイページ', user_path(current_user.id), class: "category-list" %></li>
        <li><%= link_to current_user.user_name, "#", class: "user-nickname" %></li>
       <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %> 
    </ul>
  </div>
</header>